In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("data/50_startups.csv")

X = data.iloc[:, :-1].values
y = data.iloc[:, 4].values

In [3]:
X

array([[165349.2, 136897.8, 471784.1, 'New York'],
       [162597.7, 151377.59, 443898.53, 'California'],
       [153441.51, 101145.55, 407934.54, 'Florida'],
       [144372.41, 118671.85, 383199.62, 'New York'],
       [142107.34, 91391.77, 366168.42, 'Florida'],
       [131876.9, 99814.71, 362861.36, 'New York'],
       [134615.46, 147198.87, 127716.82, 'California'],
       [130298.13, 145530.06, 323876.68, 'Florida'],
       [120542.52, 148718.95, 311613.29, 'New York'],
       [123334.88, 108679.17, 304981.62, 'California'],
       [101913.08, 110594.11, 229160.95, 'Florida'],
       [100671.96, 91790.61, 249744.55, 'California'],
       [93863.75, 127320.38, 249839.44, 'Florida'],
       [91992.39, 135495.07, 252664.93, 'California'],
       [119943.24, 156547.42, 256512.92, 'Florida'],
       [114523.61, 122616.84, 261776.23, 'New York'],
       [78013.11, 121597.55, 264346.06, 'California'],
       [94657.16, 145077.58, 282574.31, 'New York'],
       [91749.16, 114175.79, 29491

In [4]:
y

array([192261.83, 191792.06, 191050.39, 182901.99, 166187.94, 156991.12,
       156122.51, 155752.6 , 152211.77, 149759.96, 146121.95, 144259.4 ,
       141585.52, 134307.35, 132602.65, 129917.04, 126992.93, 125370.37,
       124266.9 , 122776.86, 118474.03, 111313.02, 110352.25, 108733.99,
       108552.04, 107404.34, 105733.54, 105008.31, 103282.38, 101004.64,
        99937.59,  97483.56,  97427.84,  96778.92,  96712.8 ,  96479.51,
        90708.19,  89949.14,  81229.06,  81005.76,  78239.91,  77798.83,
        71498.49,  69758.98,  65200.33,  64926.08,  49490.75,  42559.73,
        35673.41,  14681.4 ])

In [5]:
from learnML.preprocessing import OneHotEncoder

one_hot_encoder = OneHotEncoder(X, indexes=3)
X = one_hot_encoder.fit_transform()

In [6]:
one_hot_encoder.get_encodings()

{'California': array([1., 0., 0.]),
 'Florida': array([0., 1., 0.]),
 'New York': array([0., 0., 1.])}

In [7]:
from learnML.preprocessing import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [8]:
from learnML.preprocessing import ZScoreNormalization

x_scalar = ZScoreNormalization(X_train)
y_scalar = ZScoreNormalization(y_train)

x_scalar.fit()
y_scalar.fit()

In [9]:
from learnML.regression import LinearRegression

model = LinearRegression(
    learning_rate=0.005, n_iterations=100000, x_scalar=x_scalar, y_scalar=y_scalar
)
model.fit(X_train, y_train)

Iteration:       0 | Cost: 4.916935e-01
Iteration:   10000 | Cost: 2.490762e-02
Iteration:   20000 | Cost: 2.490762e-02
Iteration:   30000 | Cost: 2.490762e-02
Iteration:   40000 | Cost: 2.490762e-02
Iteration:   50000 | Cost: 2.490762e-02
Iteration:   60000 | Cost: 2.490762e-02
Iteration:   70000 | Cost: 2.490762e-02
Iteration:   80000 | Cost: 2.490762e-02
Iteration:   90000 | Cost: 2.490762e-02
Iteration:  100000 | Cost: 2.490762e-02


In [10]:
y_pred = model.predict(X_test)
np.set_printoptions(precision=2)
print(
    np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), 1)
)

[[103015.2  103282.38]
 [132582.28 144259.4 ]
 [132447.74 146121.95]
 [ 71976.1   77798.83]
 [178537.48 191050.39]
 [116161.24 105008.31]
 [ 67851.69  81229.06]
 [ 98791.73  97483.56]
 [113969.44 110352.25]
 [167921.07 166187.94]]
